version: "3"

services:
  app:
    build: .
    container_name: tereaiqos.ru # меняем на имя проекта
    restart: always
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=tereaiqos.ru # домен сайта
      - LETSENCRYPT_HOST=tereaiqos.ru # домен для SSL
      - LETSENCRYPT_EMAIL=qwe@gmail.com
    networks:
      - web
    volumes:
      # Все сайты используют одну и ту же папку с картинками
      - /var/www/iluma-store.ru/images:/app/public/images:ro
      # - /var/www/tereaiqos.ru/.next:/app/.next

networks:
  web:
    external: true
